const SERVICE_DOMAINS: Record<string, string> = {
  // Streaming & underhållning
  'netflix':          'netflix.com',
  'spotify':          'spotify.com',
  'apple tv':         'tv.apple.com',
  'disney':           'disneyplus.com',
  'hbo max':          'max.com',
  'max':              'max.com',
  'viaplay':          'viaplay.com',
  'c more':           'cmore.se',
  'youtube premium':  'youtube.com',
  'youtube':          'youtube.com',
  'tidal':            'tidal.com',
  'deezer':           'deezer.com',
  'soundcloud':       'soundcloud.com',
  'twitch':           'twitch.tv',
  'crunchyroll':      'crunchyroll.com',
  'paramount':        'paramountplus.com',
  'mubi':             'mubi.com',
  'plex':             'plex.tv',
  'skyshowtime':      'skyshowtime.com',
  'discovery':        'discoveryplus.com',
  'britbox':          'britbox.com',
  'curiosity stream': 'curiositystream.com',
  'nebula':           'nebula.tv',
  'bandcamp':         'bandcamp.com',
  'mixcloud':         'mixcloud.com',
  'beatport':         'beatport.com',

  // Apple & Google
  'icloud':           'icloud.com',
  'apple music':      'music.apple.com',
  'apple arcade':     'apple.com',
  'apple one':        'apple.com',
  'apple fitness':    'apple.com',
  'apple':            'apple.com',
  'google one':       'one.google.com',
  'google workspace': 'workspace.google.com',
  'google':           'google.com',

  // Mjukvara & produktivitet
  'adobe':            'adobe.com',
  'photoshop':        'adobe.com',
  'illustrator':      'adobe.com',
  'premiere':         'adobe.com',
  'lightroom':        'adobe.com',
  'acrobat':          'adobe.com',
  'creative cloud':   'adobe.com',
  'microsoft 365':    'microsoft.com',
  'microsoft':        'microsoft.com',
  'office 365':       'microsoft.com',
  'office':           'microsoft.com',
  'm365':             'microsoft.com',
  'o365':             'microsoft.com',
  'teams':            'microsoft.com',
  'onedrive':         'microsoft.com',
  'dropbox':          'dropbox.com',
  'notion':           'notion.so',
  'figma':            'figma.com',
  '1password':        '1password.com',
  'lastpass':         'lastpass.com',
  'nordvpn':          'nordvpn.com',
  'expressvpn':       'expressvpn.com',
  'mullvad':          'mullvad.net',
  'evernote':         'evernote.com',
  'todoist':          'todoist.com',
  'obsidian':         'obsidian.md',
  'craft':            'craft.do',
  'fantastical':      'flexibits.com',
  'setapp':           'setapp.com',
  'cleanmymac':       'macpaw.com',
  'superhuman':       'superhuman.com',
  'spark':            'sparkmailapp.com',
  'airmail':          'airmailapp.com',

  // Dev-verktyg
  'github copilot':   'github.com',
  'github':           'github.com',
  'copilot':          'github.com',
  'gitlab':           'gitlab.com',
  'vercel':           'vercel.com',
  'netlify':          'netlify.com',
  'heroku':           'heroku.com',
  'cloudflare':       'cloudflare.com',
  'aws':              'aws.amazon.com',
  'amazon web':       'aws.amazon.com',
  'google cloud':     'cloud.google.com',
  'azure':            'azure.microsoft.com',
  'jetbrains':        'jetbrains.com',
  'linear':           'linear.app',
  'jira':             'atlassian.com',
  'confluence':       'atlassian.com',
  'slack':            'slack.com',
  'zoom':             'zoom.us',
  'digitalocean':     'digitalocean.com',
  'railway':          'railway.app',
  'render':           'render.com',
  'supabase':         'supabase.com',
  'mongodb':          'mongodb.com',
  'datadog':          'datadoghq.com',
  'sentry':           'sentry.io',
  'postman':          'postman.com',
  'retool':           'retool.com',
  'airtable':         'airtable.com',
  'webflow':          'webflow.com',
  'framer':           'framer.com',
  'sanity':           'sanity.io',
  'contentful':       'contentful.com',
  'algolia':          'algolia.com',
  'twilio':           'twilio.com',
  'openai':           'openai.com',
  'chatgpt':          'openai.com',
  'gpt':              'openai.com',
  'anthropic':        'anthropic.com',
  'claude':           'anthropic.com',
  'sendgrid':         'sendgrid.com',
  'resend':           'resend.com',
  'midjourney':       'midjourney.com',
  'perplexity':       'perplexity.ai',
  'gemini':           'gemini.google.com',
  'cursor':           'cursor.sh',
  'stability':        'stability.ai',

  // Design & kreativt
  'sketch':           'sketch.com',
  'zeplin':           'zeplin.io',
  'hotjar':           'hotjar.com',
  'loom':             'loom.com',
  'canva':            'canva.com',

  // Kommunikation & projekt
  'basecamp':         'basecamp.com',
  'asana':            'asana.com',
  'monday':           'monday.com',
  'clickup':          'clickup.com',
  'trello':           'trello.com',
  'miro':             'miro.com',
  'coda':             'coda.io',
  'calendly':         'calendly.com',
  'typeform':         'typeform.com',
  'toggl':            'toggl.com',

  // Hälsa & träning
  'headspace':        'headspace.com',
  'calm':             'calm.com',
  'strava':           'strava.com',
  'myfitnesspal':     'myfitnesspal.com',
  'whoop':            'whoop.com',
  'garmin':           'garmin.com',
  'polar':            'polar.com',
  'oura':             'ouraring.com',
  'noom':             'noom.com',

  // Ekonomi
  'ynab':             'youneedabudget.com',
  'freshbooks':       'freshbooks.com',
  'harvest':          'getharvest.com',

  // Spel
  'xbox':             'xbox.com',
  'game pass':        'xbox.com',
  'playstation':      'playstation.com',
  'nintendo':         'nintendo.com',
  'ea play':          'ea.com',
  'ubisoft':          'ubisoft.com',
  'geforce':          'nvidia.com',
  'steam':            'store.steampowered.com',
  'gog':              'gog.com',
  'humble':           'humblebundle.com',

  // Utbildning
  'pluralsight':      'pluralsight.com',
  'frontend masters': 'frontendmasters.com',
  'udemy':            'udemy.com',
  'udacity':          'udacity.com',
  'masterclass':      'masterclass.com',
  'brilliant':        'brilliant.org',
  'codecademy':       'codecademy.com',
  'blinkist':         'blinkist.com',
  'duolingo':         'duolingo.com',
  'skillshare':       'skillshare.com',
  'coursera':         'coursera.org',
  'linkedin':         'linkedin.com',

  // Svenska tidningar & medier — Bonnier
  'dn':               'dn.se',
  'dagens nyheter':   'dn.se',
  'expressen':        'expressen.se',
  'di':               'di.se',
  'dagens industri':  'di.se',
  'sydsvenskan':      'sydsvenskan.se',
  'hd':               'hd.se',
  'helsingborgs':     'hd.se',

  // Svenska tidningar & medier — Schibstedt
  'svd':              'svd.se',
  'svenska dagbladet':'svd.se',
  'aftonbladet':      'aftonbladet.se',
  'omni':             'omni.se',

  // Svenska tidningar & medier — övriga
  'gp':               'gp.se',
  'göteborgs-posten': 'gp.se',
  'göteborgs posten': 'gp.se',
  'göteborgsposten':  'gp.se',
  'sr':               'sverigesradio.se',
  'sveriges radio':   'sverigesradio.se',
  'svt':              'svt.se',
  'tv4':              'tv4.se',
  'breakit':          'breakit.se',
  'realtid':          'realtid.se',
  'fokus':            'fokus.se',
  'filter':           'filtermedia.se',
  'nwt':              'nwt.se',
  'vk':               'vk.se',
  'östgöta':          'corren.se',
  'corren':           'corren.se',

  // Övrigt
  'patreon':          'patreon.com',
  'substack':         'substack.com',
  'medium':           'medium.com',
  'squarespace':      'squarespace.com',
  'wix':              'wix.com',
  'backblaze':        'backblaze.com',
  'protonmail':       'proton.me',
  'proton':           'proton.me',
  'fastmail':         'fastmail.com',
  'bitwarden':        'bitwarden.com',
  'dashlane':         'dashlane.com',
  'nordpass':         'nordpass.com',
}

// Längre nycklar testas först för att undvika att t.ex. "apple" matchar "apple tv+"
const SORTED_KEYS = Object.keys(SERVICE_DOMAINS).sort((a, b) => b.length - a.length)

export function getDomainForService(name: string): string | null {
  const lower = name.toLowerCase()
  const match = SORTED_KEYS.find((key) => lower.includes(key))
  return match ? SERVICE_DOMAINS[match] : null
}
